TaminApp/Controllers/BankController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using TaminApp.Core;
using TaminApp.Entity;
using TaminApp.ViewModels.Bank;

namespace TaminApp.Controllers
{
    public class BankController : Controller
    {
        #region Initialize
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public BankController(IUnitOfWork unitOfWork, IMapper mapper)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }
        #endregion 
        #region Index
        public async Task<IActionResult> Index()
        {
            var bank  = await _unitOfWork.Repository<Bank>()
                .GetAllAsync(w => !w.IsDelete );

            var viewModel = _mapper.Map<List<BankListViewModel>>(bank );
            return View(viewModel);
        }
        #endregion
        #region Create
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BankCreateViewModel  model)
        {
            if (ModelState.IsValid)
            {
                var existBank = await _unitOfWork.Repository<Bank >()
                    .GetAllAsync(w => w.BankName == model.BankName && !w.IsDelete );

                if (existBank.Any())
                {
                    ModelState.AddModelError("BankName", "این نام از قبل وجود دارد.");
                    return View(model);
                }

                var _bank = _mapper.Map<Bank>(model);
                _bank.RegisterDate = DateTime.Now;
                  _bank.IsActive = true;

                await _unitOfWork.BeginTransactionAsync();
                try
                {
                    await _unitOfWork.Repository<Bank>().AddAsync(_bank );
                    await _unitOfWork.CommitAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                 ModelState.AddModelError("", "خطایی در ذخیره‌سازی داده‌ها رخ داد.");
                    return View(model);
                }
            }
            return View(model);
        }
        #endregion
        #region Edit
        public async Task<IActionResult> Edit(int id)
        {
            var bank  = await _unitOfWork.Repository<Bank>().GetByIdAsync(id);
            if (bank == null || bank.IsDelete )
            {
                return NotFound();
            }
            var viewModel = _mapper.Map<BankEditViewModel>(bank);
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, BankEditViewModel model)
        {
            if (id != model.ID || !ModelState.IsValid)
            {
                return View(model);
            }

            var bank = await _unitOfWork.Repository<Bank >().GetByIdAsync(id);
            if (bank  == null || bank.IsDelete )
            {
                return NotFound();
            }

            var exsitBank = await _unitOfWork.Repository<Bank >()
                .GetAllAsync(w => w.BankName  == model.BankName  && w.ID != id && !w.IsDelete );

            if (exsitBank.Any())
            {
                ModelState.AddModelError("BankName", "این نام از قبل وجود دارد.");
                return View(model);
            }

         var _bank= _mapper.Map(model, bank );
         _bank.UpdatedDate = DateTime.Now;

            await _unitOfWork.BeginTransactionAsync();
            try
            {
                _unitOfWork.Repository<Bank>().Update(_bank );
                await _unitOfWork.CommitAsync();
              return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
            ModelState.AddModelError("", "خطایی در بروزرسانی داده‌ها رخ داد.");
                return View(model);
            }
        }
        #endregion
        #region Delete
        public async Task<IActionResult> Delete(int id)
        {
            var bank = await _unitOfWork.Repository<Bank>().GetByIdAsync(id);
            if (bank == null || bank.IsDelete )
            {
                return NotFound();
            }

          bank.IsDelete = true;

            await _unitOfWork.BeginTransactionAsync();
            try
            {
                _unitOfWork.Repository<Bank >().Update(bank );
                await _unitOfWork.CommitAsync();
               return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
               ModelState.AddModelError("", "خطایی در حذف داده‌ها رخ داد.");
                return RedirectToAction(nameof(Index));
            }
        }
        #endregion
    }
}

TaminApp/Controllers/DegreeController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using TaminApp.Core;
using TaminApp.Entity;
using TaminApp.ViewModels.Bank;
using TaminApp.ViewModels.Degree;

namespace TaminApp.Controllers
{
    public class DegreeController : Controller
    {
        #region Initialize
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public DegreeController(IUnitOfWork unitOfWork, IMapper mapper)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }
        #endregion 
        #region Index
        public async Task<IActionResult> Index()
        {
            var degree = await _unitOfWork.Repository<Degree >()
                .GetAllAsync(w => !w.IsDelete);

            var viewModel = _mapper.Map<List<DegreeListViewModel >>(degree );
            return View(viewModel);
        }
        #endregion
        #region Create
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(DegreeCreateViewModel  model)
        {
            if (ModelState.IsValid)
            {
                var existDegree = await _unitOfWork.Repository<Degree >()
                    .GetAllAsync(w => w.DegreeName == model.DegreeName  && !w.IsDelete);

                if (existDegree.Any())
                {
                    ModelState.AddModelError("DegreeName", "این نام از قبل وجود دارد.");
                    return View(model);
                }

                var _degree = _mapper.Map<Degree >(model);
                _degree.RegisterDate = DateTime.Now;
                _degree.IsActive = true;

                await _unitOfWork.BeginTransactionAsync();
                try
                {
                    await _unitOfWork.Repository<Degree>().AddAsync(_degree );
                    await _unitOfWork.CommitAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "خطایی در ذخیره‌سازی داده‌ها رخ داد.");
                    return View(model);
                }
            }
            return View(model);
        }
        #endregion
        #region Edit
        public async Task<IActionResult> Edit(int id)
        {
            var degree = await _unitOfWork.Repository<Degree>().GetByIdAsync(id);
            if (degree  == null || degree .IsDelete)
            {
                return NotFound();
            }
            var viewModel = _mapper.Map<DegreeEditViewModel >(degree );
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, DegreeEditViewModel  model)
        {
            if (id != model.ID || !ModelState.IsValid)
            {
                return View(model);
            }

            var degree = await _unitOfWork.Repository<Degree >().GetByIdAsync(id);
            if (degree  == null || degree.IsDelete)
            {
                return NotFound();
            }

            var exsitDegree = await _unitOfWork.Repository<Degree>()
                .GetAllAsync(w => w.DegreeName  == model.DegreeName  && w.ID != id && !w.IsDelete);

            if (exsitDegree.Any())
            {
                ModelState.AddModelError("DegreeName", "این نام از قبل وجود دارد.");
                return View(model);
            }

            var _degree = _mapper.Map(model,degree  );
            _degree.UpdatedDate = DateTime.Now;

            await _unitOfWork.BeginTransactionAsync();
            try
            {
                _unitOfWork.Repository<Degree>().Update(_degree);
                await _unitOfWork.CommitAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "خطایی در بروزرسانی داده‌ها رخ داد.");
                return View(model);
            }
        }
        #endregion
        #region Delete
        public async Task<IActionResult> Delete(int id)
        {
            var degree = await _unitOfWork.Repository<Degree>().GetByIdAsync(id);
            if (degree  == null || degree.IsDelete)
            {
                return NotFound();
            }

           degree.IsDelete = true;

            await _unitOfWork.BeginTransactionAsync();
            try
            {
                _unitOfWork.Repository<Degree>().Update(degree);
                await _unitOfWork.CommitAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "خطایی در حذف داده‌ها رخ داد.");
                return RedirectToAction(nameof(Index));
            }
        }
        #endregion
    }
}

TaminApp/Controllers/PeopleController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using TaminApp.Core;
using TaminApp.Entity;
using TaminApp.ViewModels.Bank;
using TaminApp.ViewModels.people;

namespace TaminApp.Controllers
{
    public class PeopleController : Controller
    {
        #region Initialize
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public PeopleController(IUnitOfWork unitOfWork, IMapper mapper)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }
        #endregion 
        #region Index
        public async Task<IActionResult> Index()
        {
            var peopel = await _unitOfWork.Repository<people>()
                .GetAllAsync(w => !w.IsDelete);

            var viewModel = _mapper.Map<List<PeopleListViewModel>>(peopel);
            return View(viewModel);
        }
        #endregion
        #region Create
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PeopleCreateViewModel  model)
        {
            if (ModelState.IsValid)
            {
                var existpeople = await _unitOfWork.Repository<people >()
                    .GetAllAsync(w => w.NationalCode  == model.NationalCode  && !w.IsDelete);

                if (existpeople.Any())
                {
                    ModelState.AddModelError("NationalCode", "این کدملی از قبل وجود دارد.");
                    return View(model);
                }

                var _people = _mapper.Map<people>(model);
                _people.RegisterDate = DateTime.Now;
                _people.IsActive = true;

                await _unitOfWork.BeginTransactionAsync();
                try
                {
                    await _unitOfWork.Repository<people >().AddAsync(_people);
                    await _unitOfWork.CommitAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "خطایی در ذخیره‌سازی داده‌ها رخ داد.");
                    return View(model);
                }
            }
            return View(model);
        }
        #endregion
        #region Edit
        public async Task<IActionResult> Edit(int id)
        {
            var bank = await _unitOfWork.Repository<Bank>().GetByIdAsync(id);
            if (bank == null || bank.IsDelete)
            {
                return NotFound();
            }
            var viewModel = _mapper.Map<BankEditViewModel>(bank);
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, BankEditViewModel model)
        {
            if (id != model.ID || !ModelState.IsValid)
            {
                return View(model);
            }

            var bank = await _unitOfWork.Repository<Bank>().GetByIdAsync(id);
            if (bank == null || bank.IsDelete)
            {
                return NotFound();
            }

            var exsitBank = await _unitOfWork.Repository<Bank>()
                .GetAllAsync(w => w.BankName == model.BankName && w.ID != id && !w.IsDelete);

            if (exsitBank.Any())
            {
                ModelState.AddModelError("BankName", "این نام از قبل وجود دارد.");
                return View(model);
            }

            var _bank = _mapper.Map(model, bank);
            _bank.UpdatedDate = DateTime.Now;

            await _unitOfWork.BeginTransactionAsync();
            try
            {
                _unitOfWork.Repository<Bank>().Update(_bank);
                await _unitOfWork.CommitAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "خطایی در بروزرسانی داده‌ها رخ داد.");
                return View(model);
            }
        }
        #endregion
        #region Delete
        public async Task<IActionResult> Delete(int id)
        {
            var bank = await _unitOfWork.Repository<Bank>().GetByIdAsync(id);
            if (bank == null || bank.IsDelete)
            {
                return NotFound();
            }

            bank.IsDelete = true;

            await _unitOfWork.BeginTransactionAsync();
            try
            {
                _unitOfWork.Repository<Bank>().Update(bank);
                await _unitOfWork.CommitAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "خطایی در حذف داده‌ها رخ داد.");
                return RedirectToAction(nameof(Index));
            }
        }
        #endregion
    }
}

TaminApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TaminApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.rtl.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TaminApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">صفحه اصلی</a>
                        </li>

                        <!-- منوی اطلاعات پایه -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" href="#" id="basicInfoDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                اطلاعات پایه
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="basicInfoDropdown">
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="People" asp-action="Index">اعضا(اشخاص) </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Bank" asp-action="Index">بانک </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Degree" asp-action="Index">مدرک تحصیلی</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="DiseaseType" asp-action="Index">نوع بیماری</a>
                                </li>
                                <li> حسابداری
                                    <ul>
                                        <li>
                                            <a class="dropdown-item" asp-area="" asp-controller="FiscalYear" asp-action="Index">حسابداری</a>
                                        </li>
                                        <li>
                                            <a class="dropdown-item" asp-area="" asp-controller="FiscalYear" asp-action="Index">حسابداری</a>
                                        </li>
                                    </ul>
                                   
                                </li>
                               
                            </ul>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" href="#" id="SabtAsnadDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                ثبت اسناد
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="SabtAsnadDropdown">
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Receipt" asp-action="Create">ثبت سوابق پزشکی و بیمه</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Transaction" asp-action="Transfer">ثبت سوابق ورزشی</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Transaction" asp-action="Consumption">ثبت سوابق ایثارگری</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Transaction" asp-action="Return">ثبت تسهیلات بانکی</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Transaction" asp-action="ReturnFromConsumption">ثبت بیمه تکمیلی</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Transaction" asp-action="ReturnFromConsumption">طرح کرامت</a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" href="#" id="warehouseOperationsDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                              حسابداری
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="warehouseOperationsDropdown">
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Receipt" asp-action="Create">دریافت از اشخاص</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Transaction" asp-action="Transfer">پرداخت به اشخاص</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Transaction" asp-action="Consumption">ثبت درهزینه ها</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Transaction" asp-action="Return">ثبت درآمد ها</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Transaction" asp-action="ReturnFromConsumption">ثبت اموال</a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">حریم خصوصی</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - TaminApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>