TaminApp/ViewModels/DiseaseType/DiseaseTypeCreateViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace TaminApp.ViewModels.DiseaseType
{
    public class DiseaseTypeCreateViewModel
    {
        [Required(ErrorMessage = "عنوان الزامی است.")]
        [MaxLength(50, ErrorMessage = "نام بیماری نمی‌تواند بیشتر از 50 کاراکتر باشد.")]

        public string DiseaseName { get; set; } //نام بیماری
    }
}

TaminApp/ViewModels/DiseaseType/DiseaseTypeEditViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace TaminApp.ViewModels.DiseaseType
{
    public class DiseaseTypeEditViewModel
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "عنوان الزامی است.")]
        [MaxLength(50, ErrorMessage = "نام بیماری نمی‌تواند بیشتر از 50 کاراکتر باشد.")]
        public string DiseaseName { get; set; } //نام بیماری
        public bool IsActive { get; set; }
    }
}

TaminApp/ViewModels/DiseaseType/ِDiseaseTypeListViewModel.cs
namespace TaminApp.ViewModels.DiseaseType
{
    public class DiseaseTypeListViewModel
    {
        public int ID { get; set; }
        public string DiseaseName { get; set; } //نام بیماری
        public bool IsActive { get; set; }
    }
}

TaminApp/Controllers/DiseaseTypeController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using TaminApp.Core;
using TaminApp.Entity;
using TaminApp.ViewModels.Degree;
using TaminApp.ViewModels.DiseaseType;

namespace TaminApp.Controllers
{
    public class DiseaseTypeController : Controller
    {
        #region Initialize
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public DiseaseTypeController(IUnitOfWork unitOfWork, IMapper mapper)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }
        #endregion 
        #region Index
        public async Task<IActionResult> Index()
        {
            var disease = await _unitOfWork.Repository<DiseaseType >()
                .GetAllAsync(w => !w.IsDelete);

            var viewModel = _mapper.Map<List<DiseaseTypeListViewModel >>(disease );
            return View(viewModel);
        }
        #endregion
        #region Create
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(DiseaseTypeCreateViewModel  model)
        {
            if (ModelState.IsValid)
            {
                var existdisease = await _unitOfWork.Repository<DiseaseType>()
                    .GetAllAsync(w => w.DiseaseName == model.DiseaseName && !w.IsDelete);

                if (existdisease.Any())
                {
                    ModelState.AddModelError("DegreeName", "این نام از قبل وجود دارد.");
                    return View(model);
                }

                var _disease = _mapper.Map<DiseaseType >(model);
                _disease.RegisterDate = DateTime.Now;
               _disease.IsActive = true;

                await _unitOfWork.BeginTransactionAsync();
                try
                {
                    await _unitOfWork.Repository<DiseaseType>().AddAsync(_disease);
                    await _unitOfWork.CommitAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "خطایی در ذخیره‌سازی داده‌ها رخ داد.");
                    return View(model);
                }
            }
            return View(model);
        }
        #endregion
        #region Edit
        public async Task<IActionResult> Edit(int id)
        {
            var disease = await _unitOfWork.Repository<DiseaseType >().GetByIdAsync(id);
            if (disease == null || disease.IsDelete)
            {
                return NotFound();
            }
            var viewModel = _mapper.Map<DiseaseTypeEditViewModel>(disease );
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, DiseaseTypeEditViewModel  model)
        {
            if (id != model.ID || !ModelState.IsValid)
            {
                return View(model);
            }

            var disease = await _unitOfWork.Repository<DiseaseType >().GetByIdAsync(id);
            if (disease  == null || disease.IsDelete)
            {
                return NotFound();
            }

            var exsitdisease = await _unitOfWork.Repository<DiseaseType >()
                .GetAllAsync(w => w.DiseaseName  == model.DiseaseName  && w.ID != id && !w.IsDelete);

            if (exsitdisease.Any())
            {
                ModelState.AddModelError("DiseaseName", "این نام از قبل وجود دارد.");
                return View(model);
            }

            var _disease = _mapper.Map(model, disease );
            _disease .UpdatedDate = DateTime.Now;

            await _unitOfWork.BeginTransactionAsync();
            try
            {
                _unitOfWork.Repository<DiseaseType >().Update(_disease );
                await _unitOfWork.CommitAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "خطایی در بروزرسانی داده‌ها رخ داد.");
                return View(model);
            }
        }
        #endregion
        #region Delete
        public async Task<IActionResult> Delete(int id)
        {
            var disease = await _unitOfWork.Repository<DiseaseType >().GetByIdAsync(id);
            if (disease  == null || disease.IsDelete)
            {
                return NotFound();
            }

           disease.IsDelete = true;

            await _unitOfWork.BeginTransactionAsync();
            try
            {
                _unitOfWork.Repository<DiseaseType>().Update(disease);
                await _unitOfWork.CommitAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "خطایی در حذف داده‌ها رخ داد.");
                return RedirectToAction(nameof(Index));
            }
        }
        #endregion
    }
}

TaminApp/Views/DiseaseType/Create.cshtml
@model TaminApp.ViewModels.DiseaseType.DiseaseTypeCreateViewModel  ;

@{
    ViewData["Title"] = "ایجادنوع بیماری جدید";
}

<h3>ایجاد نوع بیماری جدید</h3>

<form asp-action="Create" method="post">
    <div class="mb-3 row">
        <label asp-for="DiseaseName " class="col-sm-2 col-form-label">نام نوع بیماری</label>
        <div class="col-sm-10">
            <input asp-for="DiseaseName " class="form-control" />
            <span asp-validation-for="DiseaseName" class="text-bg-info"></span>
        </div>
    </div>
    <div class="mb-3 row">
        <div class="col-sm-10 offset-sm-2">
            <button type="submit" class="btn btn-primary">ایجاد</button>
            <a asp-action="Index" class="btn btn-secondary">بازگشت</a>
        </div>
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

TaminApp/Views/DiseaseType/Edit.cshtml
@model TaminApp.ViewModels.DiseaseType.DiseaseTypeEditViewModel ;

@{
    ViewData["Title"] = "ویرایش نوع بیماری";
}

<h3>ویرایش نوع بیماری</h3>

<form asp-action="Edit" method="post">
    <div class="mb-3 row">
        <label asp-for="DiseaseName " class="col-sm-2 col-form-label">نام بیماری </label>
        <div class="col-sm-10">
            <input asp-for="DiseaseName  " class="form-control" />
            <span asp-validation-for="DiseaseName " class="text-bg-info"></span>
        </div>
    </div>
    <div class="mb-3 row">
        <label asp-for="IsActive" class="col-sm-2 col-form-label">فعال</label>
        <div class="col-sm-10">
            <input asp-for="IsActive" type="checkbox" class="form-check-input" />
        </div>
    </div>
    <div class="mb-3 row">
        <div class="col-sm-10 offset-sm-2">
            <button type="submit" class="btn btn-primary">ایجاد</button>
            <a asp-action="Index" class="btn btn-secondary">بازگشت</a>
        </div>
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

TaminApp/Views/DiseaseType/Index.cshtml
@model IEnumerable<TaminApp.ViewModels.DiseaseType.DiseaseTypeListViewModel >

<h2>نام بیماری </h2>

<a href="@Url.Action("Create", "DiseaseType")" class="btn btn-primary">جدید</a>

<hr />

<table class="table">
    <thead>
        <tr>
            <th>عنوان</th>
            <th>وضعیت</th>
            <th>عملیات</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.DiseaseName </td>
                <td>@(item.IsActive ? "فعال" : "غیرفعال")</td>
                <td>
                    <a href="@Url.Action("Edit", "DiseaseType", new { id = item.ID   })" class="btn btn-warning">ویرایش</a>
                    <a href="@Url.Action("Delete", "DiseaseType", new { id = item.ID })" class="btn btn-danger">حذف</a>
                </td>
            </tr>
        }
    </tbody>
</table>